# Generated by Django 5.0.2 on 2024-02-24 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_alter_payments_payment_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payments',
            name='payment_amount',
            field=models.IntegerField(blank=True, null=True, verbose_name='сумма оплаты'),
        ),
    ]
