# Generated by Django 5.0.2 on 2024-02-25 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_alter_payments_payment_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payments',
            name='payment_session_id',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='идентификатор сессии платежа'),
        ),
    ]
