# Generated by Django 5.0.2 on 2024-02-24 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_payments_options_alter_user_options_subscribe'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payments',
            name='payment_lesson',
        ),
    ]
