# Generated by Django 5.0.2 on 2024-02-24 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_payments_payment_session_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscribe',
            name='course',
        ),
        migrations.RemoveField(
            model_name='subscribe',
            name='user',
        ),
        migrations.DeleteModel(
            name='Payments',
        ),
        migrations.DeleteModel(
            name='Subscribe',
        ),
    ]
