version: '3'

services:

  redis:
    image: redis
    ports:
      - '6379:6379'
    healthcheck:
      test: redis-cli ping
      interval: 2s
      timeout: 2s
      retries: 10

  db:
    image: postgres
    env_file:
      - .env
    environment:
        - POSTGRES_USER=${DATABASES_USER}
        - POSTGRES_PASSWORD=${DATABASES_PASSWORD}
        - POSTGRES_DB=${DATABASES_NAME}
        - PGDATA=/var/lib/postgresql/data/pgdata

    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}" ]
      interval: 10s
      timeout: 5s
      retries: 5

    volumes:
      - pg_data:/var/lib/postgresql/data/pgdata
    ports:
      - '5432:5432'

  app:
    build: .
    tty: true
    command: bash -c "python3 manage.py migrate && python3 manage.py runserver 0.0.0.0:8000"
    ports:
      - '8000:8000'
    env_file:
      - .env
    environment:
      DATABASE_HOST: db
      CACHE_LOCATION: 'redis://redis:6379/'
      CELERY_BROKER_URL: 'redis://redis:6379/0'
      CELERY_RESULT_BACKEND: 'redis://redis:6379/0'

    volumes:
      - .:/code


  celery:
    build: .
    tty: true
    env_file:
      - .env
    environment:
      DATABASE_HOST: db
      CACHE_LOCATION: 'redis://redis:6379/0'
      CELERY_BROKER_URL: 'redis://redis:6379/0'
      CELERY_RESULT_BACKEND: 'redis://redis:6379/0'
    command: celery -A config worker -l INFO
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy


  celery_beat:
    build: .
    tty: true
    env_file:
      - .env
    command: celery -A config beat -l INFO
    depends_on:
      - redis
      - app


volumes:
  pg_data:

