# Generated by Django 5.0.1 on 2024-02-07 13:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_course', models.CharField(max_length=50, verbose_name='название курса')),
                ('image', models.ImageField(blank=True, null=True, upload_to='media/', verbose_name='картинка курса')),
                ('description', models.CharField(max_length=500, verbose_name='описание курса')),
            ],
            options={
                'verbose_name': 'курс',
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_lesson', models.CharField(max_length=50, verbose_name='название урока')),
                ('image', models.ImageField(upload_to='media/', verbose_name='картинка урока')),
                ('description', models.TextField(verbose_name='описание урока')),
                ('link', models.CharField(max_length=50, verbose_name='ссылка на видео')),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='materials.course', verbose_name='курс')),
            ],
            options={
                'verbose_name': 'урок',
            },
        ),
    ]
