# Generated by Django 5.0.1 on 2024-02-12 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0002_course_auther_lesson_auther'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='auther',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='lesson',
            old_name='auther',
            new_name='author',
        ),
    ]
