# Generated by Django 5.0.2 on 2024-02-20 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0003_rename_auther_course_author_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/', verbose_name='картинка урока'),
        ),
    ]
